name: Test

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version:
        - 1.15.x
        - 1.16.x
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: go install .
    - name: Lint
      id: lint
      uses: golangci/golangci-lint-action@v2.5.1
      with:
        version: v1.37
        skip-go-installation: true
        skip-pkg-cache: true
        skip-build-cache: true
      continue-on-error: true
    - name: Test
      run: go test -v -count 1 -coverprofile coverage.out ./...
    - name: Gcov to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.8
      if: "matrix.os == 'ubuntu-latest'"
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
      if: "matrix.os == 'ubuntu-latest'"
    - name: Lint result
      if: steps.lint.outcome != 'success'
      run: exit 1
    - name: Generate options and execute
      if: "matrix.os != 'windows-latest'"
      run: |
        gopt --name sample --options foo:string,bar:int,baz:bool --package main -o test/cmd/buildtest/options.go
        go build -tags test ./test/cmd/buildtest
        result="$(./buildtest)"
        want='&main.test{required:"required", foo:"foo", bar:1, baz:true}'
        if [ "${result}" != "${want}" ]; then
          echo "unexpected result: ${result}, want: ${want}"
          exit 1
        fi
